vl/apps/lab_queue/urls.py
from django.urls import path

from . import views as lab_queue_views
from django.contrib.auth import views as auth_views

app_name = 'lab_queue'
urlpatterns = [
    path('', lab_queue_views.index, name='index'),
    path('<int:queue_id>/', lab_queue_views.detail, name='detail'),
    path('register/', lab_queue_views.register, name='register'),
    path('editqueue/<int:queue_id>/', lab_queue_views.editqueue, name='editqueue'),
    path('account/', lab_queue_views.account, name='account'),
    path('newqueue/', lab_queue_views.newqueue, name='newqueue'),
    path('login/', auth_views.LoginView.as_view(template_name='lab_queue/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='lab_queue/logout.html'), name='logout'),
    path('activation/<str:user_activation_key>/', lab_queue_views.activation, name='activation'),
]

vl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('lab_queue/', include('lab_queue.urls'))
]

vl/apps/lab_queue/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.mail import send_mail
from django.contrib.postgres.fields import ArrayField
from django.conf import settings
from django.contrib.postgres.indexes import BrinIndex


from django.template.loader import render_to_string
from django.utils.html import strip_tags
# Create your models here.


class Queue(models.Model):
    queue_id = models.AutoField(primary_key=True, db_index=True)
    queue_title = models.CharField('название очереди', max_length=100)
    queue_group = models.IntegerField('номер группы')
    queue_info = models.TextField('дополнительная информация', blank=True)
    queue_create_date = models.DateTimeField(
        'дата создания', auto_now_add=True, blank=True)
    queue_enter_date = models.DateTimeField(
        'дата и время открытия очереди', default=timezone.now, blank=False)
    queue_priorities = ArrayField(models.CharField(
        max_length=50, blank=True), default=list, blank=True)
    queue_sort_by_enter_time = models.BooleanField(
        'сортировать по времени вхождения', blank=True, default=False)

    def __str__(self):
        return f'{self.queue_id} {self.queue_title}'

    class Meta:
        verbose_name = 'Queue'
        verbose_name_plural = 'Queues'
        indexes = (
            BrinIndex(fields=['queue_id']),
        )


class UserInQueue(models.Model):
    queue_id = models.AutoField(primary_key=True, db_index=True)
    uiq_user_id = models.IntegerField('id пользователя')
    uiq_queue_id = models.ForeignKey(Queue, on_delete=models.CASCADE)
    uiq_info = models.TextField(
        'дополнительная информация', blank=True, default='')
    uiq_group = models.IntegerField(
        'группа пользователя', blank=True, default=0)
    uiq_first_name = models.CharField(
        'имя пользователя', max_length=100, blank=True, default='')
    uiq_second_name = models.CharField(
        'фамилия пользователя', max_length=100, blank=True, default='')
    uiq_want_to_swap = models.BooleanField(
        'хочет ли поменяться местами', blank=True, default=False)
    uiq_index = models.IntegerField(
        'порядковый номер в очереди', blank=False, default=0)
    uiq_priorities = ArrayField(models.CharField(
        max_length=50, blank=True), default=list, blank=True)

    def __str__(self):
        return f'user {self.uiq_user_id} in queue {self.uiq_queue_id}'

    class Meta:
        verbose_name = 'User in queue'
        verbose_name_plural = 'Users in queues'
        indexes = (
            BrinIndex(fields=['queue_id']),
        )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #teacher, headman, student
    user_type = models.CharField('тип пользователя', max_length=20, blank=True)
    user_group = models.IntegerField('группа пользователя', blank=True)

    def __str__(self):
        return f'{self.user} {self.user_type} {self.user_group}'

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

class EmailConfirmed(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_activation_key = models.CharField(max_length=200, db_index=True)
    user_verified = models.BooleanField('активирован ли аккаунт', default=False)

    def __str__(self):
        return str(self.user_verified)

    class Meta:
        verbose_name = 'Email Confirmed'
        verbose_name_plural = 'Emails Confirmed'
        indexes = (
            BrinIndex(fields=['user_activation_key']),
        )
    
    def activate_user_email(self, request):
        # https://labqueueisp.herokuapp.com/lab_queue/
        user_activation_url = '/lab_queue/activation/%s'%(self.user_activation_key)
        context = {
            'user_activation_key': self.user_activation_key,
            'user_activation_url': user_activation_url,
            'request': request
        }
        subject = 'Подтверждение аккаунта на сайте с очередями'
        message = render_to_string('lab_queue/activation.html', context)
        to_list = [self.user.email, settings.EMAIL_HOST, ]
        self.email_user(subject, message,settings.EMAIL_HOST, settings.EMAIL_HOST_USER)

    def email_user(self, subject, message, from_email='From <labqueueisp@gmail.com>', *args, **kwargs):
        send_mail(subject, message, from_email, [self.user.email], **kwargs)

    

class Chat(models.Model):
    chat_id = models.AutoField(primary_key=True, db_index=True)
    chat_queue_id = models.ForeignKey(Queue, on_delete=models.CASCADE)

    def __str__(self):
        return f'Chat with id: {self.chat_id} in queue with id: {self.chat_queue_id}'

    class Meta:
        verbose_name = 'Chat'
        verbose_name_plural = 'Chats'
        indexes = (
            BrinIndex(fields=['chat_id']),
        )

class Message(models.Model):
    message_id = models.AutoField(primary_key=True, db_index=True)
    message_chat_id = models.ForeignKey(Chat, on_delete=models.CASCADE)
    message_user_id = models.IntegerField('id отправителя', blank=False)
    message_text = models.CharField('текст сообщения', max_length=1000, blank=True, default='')
    message_date = models.DateTimeField('дата отправления', auto_now_add=True, blank=True)

    def __str__(self):
        return f'Message with id: {self.message_id} in queue with id: {self.message_chat_id}'

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'
        indexes = (
            BrinIndex(fields=['message_id']),
        )

vl/apps/lab_queue/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse

from django import forms
from django.utils import timezone

from django.core.mail import send_mail
from django.template.loader import render_to_string

from django.forms import formset_factory

from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm, ProfileForm, QueueEnterForm, ChangeQueueIndexForm, ChangeInfoForm, NewQueueForm, ConfirmForm, EditQueueForm, EditUserForm, PriorityForm, StatusCheckBoxField, PriorityChoiceForm

from .other import swap_instances_index, is_mobile, get_hash

from django.contrib.auth.models import User
from .models import Queue, UserInQueue, Profile, EmailConfirmed
from django.contrib.auth.decorators import login_required

from .queue_log import QueueLogger


def index(request):
    overall_list = Queue.objects.order_by('queue_create_date')
    return render(request, 'lab_queue/mainlist.html', {'overall_list': overall_list})


@login_required
def detail(request, queue_id):
    QueueLogger.createLog('enter', user=request.user)
    try:
        queue_enter_form = QueueEnterForm()
        queue_sort_by_enter_date_form = StatusCheckBoxField()

        queue = Queue.objects.get(queue_id=queue_id)
        
        queue_priorities = []
        for choice in queue.queue_priorities: queue_priorities.append(list(eval(choice))[1])

        user_can_enter = timezone.now() > queue.queue_enter_date
        user_can_enter_remain = queue.queue_enter_date - timezone.now()
        users = UserInQueue.objects.filter(
            uiq_queue_id=queue_id).order_by('uiq_index')
        current_user = list(
            filter(lambda item: item.uiq_user_id == request.user.id, users))
        context = {
            'queue': queue,
            'users': users,
            'user_can_enter': user_can_enter,
            'user_can_enter_remain': user_can_enter_remain,
            'queue_priorities' : queue_priorities
        }
        if request.method == 'POST':
            if 'queue_enter' in request.POST:
                queue_enter_form = QueueEnterForm(request.POST)
                if len(current_user) != 0:
                    # context.update({
                    #     'current_user': current_user[0],
                    #     'queue_enter_form': queue_enter_form
                    # })
                    return render(request, 'lab_queue/detail.html', context)
                info = queue_enter_form.cleaned_data.get(
                    'uiq_info') if queue_enter_form.is_valid() else ''
                
                
                priorities, chosen_priorities_labels = [],[]
                for choice in queue.queue_priorities: priorities.append(list(eval(choice)))
                for chosen in request.POST.getlist('choices'):
                    for item in priorities:
                        if item[0] == chosen:
                            chosen_priorities_labels.append(item[1])
                new_user_in_queue = UserInQueue(
                    uiq_user_id=request.user.id,
                    uiq_queue_id=queue,
                    uiq_info=info,
                    uiq_group=request.user.profile.user_group,
                    uiq_first_name=request.user.first_name,
                    uiq_second_name=request.user.last_name,
                    uiq_priorities=chosen_priorities_labels,
                    uiq_index=len(users) + 1
                )
                messages.success(
                    request, f'{request.user.first_name}, Вы вошли в очередь, удачи подождать.')
                new_user_in_queue.save()
            elif 'queue_exit' in request.POST:
                user_to_exit = UserInQueue.objects.get(
                    uiq_user_id=request.user.id, uiq_queue_id=queue_id)
                other_users = UserInQueue.objects.filter(
                    uiq_queue_id=user_to_exit.uiq_queue_id, uiq_index__gt=user_to_exit.uiq_index)
                for user in other_users:
                    user.uiq_index -= 1
                    user.save()
                user_to_exit.delete()
                messages.success(
                    request, f'{request.user.first_name}, Вы успешно покинули очередь, хоть и непонятно зачем.')
            elif 'queue_swap_state' in request.POST:
                user_to_swap = UserInQueue.objects.filter(
                    uiq_user_id=request.user.id, uiq_queue_id=queue_id)
                value = user_to_swap[0].uiq_want_to_swap
                if value:
                    user_to_swap.update(uiq_want_to_swap=False)
                else:
                    user_to_swap.update(uiq_want_to_swap=True)
            elif 'queue_swap' in request.POST:
                form = ChangeQueueIndexForm(request.POST)
                if form.is_valid():
                    queue_swap_id = form.cleaned_data.get('queue_swap')
                    user_to_swap = UserInQueue.objects.filter(
                        uiq_user_id=queue_swap_id, uiq_queue_id=queue_id)[0]
                    user = UserInQueue.objects.filter(
                        uiq_user_id=request.user.id, uiq_queue_id=queue_id)[0]
                    if user_to_swap.uiq_want_to_swap:
                        user, user_to_swap = swap_instances_index(
                            user, user_to_swap)
                        user_to_swap.save()
                        user.save()
                        messages.success(
                            request, f'{request.user.first_name}, у Вас получилось поменяться местами!')
                    else:
                        messages.error(
                            request, f'{request.user.first_name}, не получилось поменяться местами!')
            elif 'queue_change_info' in request.POST:
                form = ChangeInfoForm(request.POST)
                if form.is_valid():
                    uiq_info = form.cleaned_data.get('uiq_info')
                    uiq_user = UserInQueue.objects.filter(uiq_user_id=request.user.id, uiq_queue_id=queue_id)[0]

                    priorities, chosen_priorities_labels = [],[]
                    for choice in queue.queue_priorities: priorities.append(list(eval(choice)))
                    for chosen in request.POST.getlist('choices'):
                        for item in priorities:
                            if item[0] == chosen:
                                chosen_priorities_labels.append(item[1])

                    uiq_user.uiq_priorities = chosen_priorities_labels
                    uiq_user.uiq_info = uiq_info
                    uiq_user.save()
                    messages.success(request, f'{request.user.first_name}, вы изменили дополнительную информацию.')
            elif 'queue_move_up' in request.POST:
                form = ChangeQueueIndexForm(request.POST)
                if form.is_valid():
                    queue_swap_id = form.cleaned_data.get('queue_move_up')
                    user = UserInQueue.objects.filter(
                        uiq_user_id=queue_swap_id, uiq_queue_id=queue_id)[0]
                    user_to_swap = UserInQueue.objects.filter(
                        uiq_queue_id=user.uiq_queue_id, uiq_index=int(user.uiq_index) - 1)
                    if len(user_to_swap) != 0:
                        user_to_swap = user_to_swap[0]
                        user, user_to_swap = swap_instances_index(
                            user, user_to_swap)
                        user.save()
                        user_to_swap.save()
                        messages.success(
                            request, f'{request.user.first_name}, Вы успешно поменяли местами.')
                    else:
                        messages.error(
                            request, f'{request.user.first_name}, не получилось поменять местами!')
            elif 'queue_move_down' in request.POST:
                form = ChangeQueueIndexForm(request.POST)
                if form.is_valid():
                    queue_swap_id = form.cleaned_data.get('queue_move_down')
                    user = UserInQueue.objects.filter(
                        uiq_user_id=queue_swap_id, uiq_queue_id=queue_id)[0]
                    user_to_swap = UserInQueue.objects.filter(
                        uiq_queue_id=user.uiq_queue_id, uiq_index=int(user.uiq_index) + 1)
                    if len(user_to_swap) != 0:
                        user_to_swap = user_to_swap[0]
                        user, user_to_swap = swap_instances_index(
                            user, user_to_swap)
                        user.save()
                        user_to_swap.save()
                        messages.success(
                            request, f'{request.user.first_name}, Вы успешно поменяли местами.')
                    else:
                        messages.error(
                            request, f'{request.user.first_name}, не получилось поменять местами!')
            elif 'queue_delete_start' in request.POST:
                form = ConfirmForm(request.POST)
                if form.is_valid():
                    context.update({'queue_delete_start': True})
                    return render(request, 'lab_queue/detail.html', context)
            elif 'queue_delete_confirm_true' in request.POST:
                form = ConfirmForm(request.POST)
                if form.is_valid():
                    uiq_queue_id = form.cleaned_data.get(
                        'queue_delete_confirm_true')
                    queue_to_delete = Queue.objects.get(queue_id=uiq_queue_id)
                    if queue_to_delete:
                        queue_to_delete.delete()
                        messages.success(
                            request, f'{request.user.first_name}, Вы успешно удалили очередь.')
                    else:
                        messages.error(

vl/templates/base (copy).html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap standart settings -->
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.min.css'%}">

    <title>{% block title %} Очереди на лабки {% endblock title %}</title>
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel sticky-top">
            <div class="container" style="max-width: 85%;">
                <a class="navbar-brand mr-4" href="/lab_queue">Очереди</a>
                <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> -->
                <div class="navbar-nav mr-auto">
                    {% if user.profile.type != 'student' %}
                        <a class="nav-item nav-link" href="{% url 'lab_queue:newqueue' %}">Новая очередь</a>
                    {% endif %}
                </div>
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'lab_queue:logout' %}">Выйти</a>
                        <a class="nav-item nav-link" href="{% url 'lab_queue:account' %}">Мой аккаунт</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'lab_queue:login' %}">Войти</a>
                        <a class="nav-item nav-link" href="{% url 'lab_queue:register' %}">Зарегистрироваться</a>
                    {% endif%}
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container" style="max-width: 85%; padding-top: 15px; background-color: #fafafa;">
        {% if messages %}
                {% for message in messages %}
                    <div class="alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        <div class="row">
            {% block content %}{% endblock %}
        </div>
        
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Gijgo scripts -->
    <script src="{% static 'js/gijgo.js'%}" charset="utf-8"></script>
    <script src="{% static 'js/gijgo.min.js'%}" charset="utf-8"></script>
    <script>
        $('#id_queue_enter_date').datetimepicker(
            {
                format: 'yyyy-mm-dd HH:MM',
                footer: true,
                modal: true,
                uiLibrary: 'bootstrap4',
                iconsLibrary: 'materialicons'
            }
        );
    </script>
</body>
</html>

vl/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap standart settings -->
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.min.css'%}">

    <title>{% block title %} Очереди на лабки {% endblock title %}</title>
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel sticky-top">
            <div class="container" style="max-width: 85%;">
                <a class="navbar-brand mr-4" href="/lab_queue">Очереди</a>
                <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> -->
                <div class="navbar-nav mr-auto">
                    {% if user.profile.type != 'student' %}
                        <a class="nav-item nav-link" href="{% url 'lab_queue:newqueue' %}">Новая очередь</a>
                    {% endif %}
                </div>
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'lab_queue:logout' %}">Выйти</a>
                        <a class="nav-item nav-link" href="{% url 'lab_queue:account' %}">Мой аккаунт</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'lab_queue:login' %}">Войти</a>
                        <a class="nav-item nav-link" href="{% url 'lab_queue:register' %}">Зарегистрироваться</a>
                    {% endif%}
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container" style="max-width: 85%; padding-top: 15px; background-color: #fafafa;">
        {% if messages %}
                {% for message in messages %}
                    <div class="alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        <div class="row">
            {% block content %}{% endblock %}
        </div>
        
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Gijgo scripts -->
    <script src="{% static 'js/gijgo.js'%}" charset="utf-8"></script>
    <script src="{% static 'js/gijgo.min.js'%}" charset="utf-8"></script>
    <script>
        $('#id_queue_enter_date').datetimepicker(
            {
                format: 'yyyy-mm-dd HH:MM',
                footer: true,
                modal: true,
                uiLibrary: 'bootstrap4',
                iconsLibrary: 'materialicons'
            }
        );
    </script>
</body>
</html>