vl/apps/lab_queue/urls.py
from django.urls import path

from . import views as lab_queue_views
from django.contrib.auth import views as auth_views

app_name = 'lab_queue'
urlpatterns = [
    path('', lab_queue_views.index, name='index'),
    path('<int:queue_id>/', lab_queue_views.detail, name='detail'),
    path('register/', lab_queue_views.register, name='register'),
    path('editqueue/<int:queue_id>/', lab_queue_views.editqueue, name='editqueue'),
    path('account/', lab_queue_views.account, name='account'),
    path('newqueue/', lab_queue_views.newqueue, name='newqueue'),
    path('login/', auth_views.LoginView.as_view(template_name='lab_queue/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='lab_queue/logout.html'), name='logout'),
    path('activation/<str:user_activation_key>/', lab_queue_views.activation, name='activation'),
]

vl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('lab_queue/', include('lab_queue.urls'))
]

vl/apps/lab_queue/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import ugettext_lazy as _
from .models import Profile, UserInQueue, Queue
from django.forms import formset_factory

from django.contrib.postgres.fields import ArrayField
from django.db import models



class DateInput(forms.DateInput):
    input_type = 'time'


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(required=True, label='Имя')
    last_name = forms.CharField(required=True, label='Фамилия')
    email = forms.CharField(required=True, label='Почта', help_text=_('На почту будет отправлена ссылка для активации аккаунта'))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name',
                  'last_name', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)

        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()

        return user


TYPE_CHOISES_RU = [
    ('student', 'Студент'),
    ('teacher', 'Преподаватель'),
    ('headman', 'Староста'),
]


class ProfileForm(forms.ModelForm):
    user_type = forms.CharField(
        label=_('Тип пользователя'),
        widget=forms.TextInput(attrs={'readonly':'readonly'}),
        initial='student'
    )
    user_group = forms.IntegerField(
        label=_('Группа'),
        help_text=_('В полной форме (85350?)')
    )

    class Meta:
        model = Profile
        fields = ['user_group', 'user_type']


class NewQueueForm(forms.ModelForm):
    queue_enter_date = forms.DateTimeField(
        label='Дата и время открытия очереди', required=False,
        widget=forms.DateTimeInput
    )
    class Meta:
        model = Queue
        fields = ['queue_title', 'queue_group', 'queue_info',
                  'queue_enter_date']

class StatusCheckBoxField(forms.Form):
    status = forms.BooleanField(widget=forms.CheckboxInput(attrs={'onclick':'this.form.submit();'}),required=False, label="")

class PriorityForm(forms.Form):
    priority = forms.CharField(
        required = False, label=''
    )

class PriorityChoiceForm(forms.Form):
    choices = forms.MultipleChoiceField(
            choices=(),
            widget=forms.CheckboxSelectMultiple(
                choices=(),
                attrs={'class':'nobull'},
            ),
            label='Приоритеты',
            required=False
    )

    def __init__(self, choices, *args, **kwargs):
        super(PriorityChoiceForm, self).__init__(*args, **kwargs)
        # label_choices = []
        # for choice in choices: label_choices.append(list(eval(choice))[1])
        self.fields['choices'].choices = choices   
    

class EditQueueForm(forms.ModelForm):
    queue_title = forms.CharField(label='Название очереди', required=True)
    queue_group = forms.IntegerField(label='Целевая группа', required=True)
    queue_info = forms.CharField(
        label='Дополнительная информация', required=False)
    queue_enter_date = forms.DateTimeField(
        label='Дата и время открытия очереди', required=False,
        widget=forms.DateTimeInput
    )

    class Meta:
        model = Queue
        fields = ['queue_title', 'queue_group',
                  'queue_info', 'queue_enter_date']


class EditUserForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        del self.fields['password']

    class Meta:
        model = User
        fields = ('username','email', 'first_name', 'last_name')


class QueueEnterForm(forms.ModelForm):
    uiq_info = forms.CharField(required=False, label='Дополнительная информация')
    class Meta:
        model = UserInQueue
        fields = ['uiq_info']


class ChangeQueueIndexForm(forms.Form):
    queue_swap = forms.CharField(required=False)
    queue_move_up = forms.CharField(required=False)
    queue_move_down = forms.CharField(required=False)


class ChangeInfoForm(forms.Form):
    uiq_info = forms.CharField(required=False)


class ConfirmForm(forms.Form):
    queue_delete_start = forms.BooleanField(required=False)
    queue_delete_confirm_true = forms.IntegerField(required=False)
    queue_delete_confirm_false = forms.BooleanField(required=False)

class SendMailForm(forms.Form):
    send_mail_subject = forms.CharField()
    send_mail_text = forms.CharField(widget=forms.Textarea())

vl/apps/lab_queue/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse

from django import forms
from django.utils import timezone

from django.core.mail import send_mail
from django.template.loader import render_to_string

from django.forms import formset_factory

from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm, ProfileForm, QueueEnterForm, ChangeQueueIndexForm, ChangeInfoForm, NewQueueForm, ConfirmForm, EditQueueForm, EditUserForm, PriorityForm, StatusCheckBoxField, PriorityChoiceForm

from .other import swap_instances_index, is_mobile, get_hash

from django.contrib.auth.models import User
from .models import Queue, UserInQueue, Profile, EmailConfirmed
from django.contrib.auth.decorators import login_required

from .queue_log import QueueLogger


def index(request):
    overall_list = Queue.objects.order_by('queue_create_date')
    return render(request, 'lab_queue/mainlist.html', {'overall_list': overall_list})


@login_required
def detail(request, queue_id):
    QueueLogger.createLog('enter', user=request.user)
    try:
        queue_enter_form = QueueEnterForm()
        queue_sort_by_enter_date_form = StatusCheckBoxField()

        queue = Queue.objects.get(queue_id=queue_id)
        
        queue_priorities = []
        for choice in queue.queue_priorities: queue_priorities.append(list(eval(choice))[1])

        user_can_enter = timezone.now() > queue.queue_enter_date
        user_can_enter_remain = queue.queue_enter_date - timezone.now()
        users = UserInQueue.objects.filter(
            uiq_queue_id=queue_id).order_by('uiq_index')
        current_user = list(
            filter(lambda item: item.uiq_user_id == request.user.id, users))
        context = {
            'queue': queue,
            'users': users,
            'user_can_enter': user_can_enter,
            'user_can_enter_remain': user_can_enter_remain,
            'queue_priorities' : queue_priorities
        }
        if request.method == 'POST':
            if 'queue_enter' in request.POST:
                queue_enter_form = QueueEnterForm(request.POST)
                if len(current_user) != 0:
                    # context.update({
                    #     'current_user': current_user[0],
                    #     'queue_enter_form': queue_enter_form
                    # })
                    return render(request, 'lab_queue/detail.html', context)
                info = queue_enter_form.cleaned_data.get(
                    'uiq_info') if queue_enter_form.is_valid() else ''
                
                
                priorities, chosen_priorities_labels = [],[]
                for choice in queue.queue_priorities: priorities.append(list(eval(choice)))
                for chosen in request.POST.getlist('choices'):
                    for item in priorities:
                        if item[0] == chosen:
                            chosen_priorities_labels.append(item[1])
                new_user_in_queue = UserInQueue(
                    uiq_user_id=request.user.id,
                    uiq_queue_id=queue,
                    uiq_info=info,
                    uiq_group=request.user.profile.user_group,
                    uiq_first_name=request.user.first_name,
                    uiq_second_name=request.user.last_name,
                    uiq_priorities=chosen_priorities_labels,
                    uiq_index=len(users) + 1
                )
                messages.success(
                    request, f'{request.user.first_name}, Вы вошли в очередь, удачи подождать.')
                new_user_in_queue.save()
            elif 'queue_exit' in request.POST:
                user_to_exit = UserInQueue.objects.get(
                    uiq_user_id=request.user.id, uiq_queue_id=queue_id)
                other_users = UserInQueue.objects.filter(
                    uiq_queue_id=user_to_exit.uiq_queue_id, uiq_index__gt=user_to_exit.uiq_index)
                for user in other_users:
                    user.uiq_index -= 1
                    user.save()
                user_to_exit.delete()
                messages.success(
                    request, f'{request.user.first_name}, Вы успешно покинули очередь, хоть и непонятно зачем.')
            elif 'queue_swap_state' in request.POST:
                user_to_swap = UserInQueue.objects.filter(
                    uiq_user_id=request.user.id, uiq_queue_id=queue_id)
                value = user_to_swap[0].uiq_want_to_swap
                if value:
                    user_to_swap.update(uiq_want_to_swap=False)
                else:
                    user_to_swap.update(uiq_want_to_swap=True)
            elif 'queue_swap' in request.POST:
                form = ChangeQueueIndexForm(request.POST)
                if form.is_valid():
                    queue_swap_id = form.cleaned_data.get('queue_swap')
                    user_to_swap = UserInQueue.objects.filter(
                        uiq_user_id=queue_swap_id, uiq_queue_id=queue_id)[0]
                    user = UserInQueue.objects.filter(
                        uiq_user_id=request.user.id, uiq_queue_id=queue_id)[0]
                    if user_to_swap.uiq_want_to_swap:
                        user, user_to_swap = swap_instances_index(
                            user, user_to_swap)
                        user_to_swap.save()
                        user.save()
                        messages.success(
                            request, f'{request.user.first_name}, у Вас получилось поменяться местами!')
                    else:
                        messages.error(
                            request, f'{request.user.first_name}, не получилось поменяться местами!')
            elif 'queue_change_info' in request.POST:
                form = ChangeInfoForm(request.POST)
                if form.is_valid():
                    uiq_info = form.cleaned_data.get('uiq_info')
                    uiq_user = UserInQueue.objects.filter(uiq_user_id=request.user.id, uiq_queue_id=queue_id)[0]

                    priorities, chosen_priorities_labels = [],[]
                    for choice in queue.queue_priorities: priorities.append(list(eval(choice)))
                    for chosen in request.POST.getlist('choices'):
                        for item in priorities:
                            if item[0] == chosen:
                                chosen_priorities_labels.append(item[1])

                    uiq_user.uiq_priorities = chosen_priorities_labels
                    uiq_user.uiq_info = uiq_info
                    uiq_user.save()
                    messages.success(request, f'{request.user.first_name}, вы изменили дополнительную информацию.')
            elif 'queue_move_up' in request.POST:
                form = ChangeQueueIndexForm(request.POST)
                if form.is_valid():
                    queue_swap_id = form.cleaned_data.get('queue_move_up')
                    user = UserInQueue.objects.filter(
                        uiq_user_id=queue_swap_id, uiq_queue_id=queue_id)[0]
                    user_to_swap = UserInQueue.objects.filter(
                        uiq_queue_id=user.uiq_queue_id, uiq_index=int(user.uiq_index) - 1)
                    if len(user_to_swap) != 0:
                        user_to_swap = user_to_swap[0]
                        user, user_to_swap = swap_instances_index(
                            user, user_to_swap)
                        user.save()
                        user_to_swap.save()
                        messages.success(
                            request, f'{request.user.first_name}, Вы успешно поменяли местами.')
                    else:
                        messages.error(
                            request, f'{request.user.first_name}, не получилось поменять местами!')
            elif 'queue_move_down' in request.POST:
                form = ChangeQueueIndexForm(request.POST)
                if form.is_valid():
                    queue_swap_id = form.cleaned_data.get('queue_move_down')
                    user = UserInQueue.objects.filter(
                        uiq_user_id=queue_swap_id, uiq_queue_id=queue_id)[0]
                    user_to_swap = UserInQueue.objects.filter(
                        uiq_queue_id=user.uiq_queue_id, uiq_index=int(user.uiq_index) + 1)
                    if len(user_to_swap) != 0:
                        user_to_swap = user_to_swap[0]
                        user, user_to_swap = swap_instances_index(
                            user, user_to_swap)
                        user.save()
                        user_to_swap.save()
                        messages.success(
                            request, f'{request.user.first_name}, Вы успешно поменяли местами.')
                    else:
                        messages.error(
                            request, f'{request.user.first_name}, не получилось поменять местами!')
            elif 'queue_delete_start' in request.POST:
                form = ConfirmForm(request.POST)
                if form.is_valid():
                    context.update({'queue_delete_start': True})
                    return render(request, 'lab_queue/detail.html', context)
            elif 'queue_delete_confirm_true' in request.POST:
                form = ConfirmForm(request.POST)
                if form.is_valid():
                    uiq_queue_id = form.cleaned_data.get(
                        'queue_delete_confirm_true')
                    queue_to_delete = Queue.objects.get(queue_id=uiq_queue_id)
                    if queue_to_delete:
                        queue_to_delete.delete()
                        messages.success(
                            request, f'{request.user.first_name}, Вы успешно удалили очередь.')
                    else:
                        messages.error(

vl/templates/lab_queue/activation.html
Здравствуйте,

Пожалуйста, активируйте ваш аккаунт по этой ссылке: 
{% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}{{ object.get_absolute_url }}{{ user_activation_url }}

Спасибо!

Ваш любимый сайт с очередями.

vl/templates/lab_queue/detail (copy).html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block title %}{{queue.queue_title}}{% endblock %}
{% block content %}
    <div class="col-sm-7 shadow content-section" style="background-color: white;">
        <div>
            <div style="float: left;">
                <h1>{{queue.queue_title}}, {{queue.queue_group}}</h1>
                <p>{{queue.queue_info}}</p>
            </div>
            <div style="float: right; margin: 10px">
                {{test}}
                {% if user.profile.user_type == 'headman' or user.profile.user_type == 'teacher' and user.profile.user_group == queue.queue_group %}
                    <form action="{% url 'lab_queue:editqueue' queue.queue_id %}"> {% csrf_token %}
                        <button class="button_main_empty" title="Изменить описание очереди" type="submit">✎</button>
                    </form>
                {% endif %}
                </form>
                <form action=""> {% csrf_token %}
                    <button class="button_main_empty" title="Обновить страницу" type="submit">↻</button>
                </form>
            </div>
        </div>
        {% if users %}
            <table class="table table-striped table-hover table-responsive table-light">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Фамилия</th>
                    <th scope="col">Группа</th>
                    <th scope="col">Доп. информация</th>
                    <th scope="col">Управление</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user_in_queue in users %}
                    <tr class="{% if user_in_queue.uiq_user_id == user.id %}user_in_queue{% endif %}">
                        <th scope="row">{{user_in_queue.uiq_index}}</th>
                        <td>{{user_in_queue.uiq_first_name}}</td>
                        <td>{{user_in_queue.uiq_second_name}}</td>
                        <td>{{user_in_queue.uiq_group}}</td>
                        <td>
                            {% for priority in user_in_queue.uiq_priorities %}
                                <small class="tag_priority">{{priority}}</small>
                            {% endfor %}
                            {{user_in_queue.uiq_info}}
                        </td>
                        <td>
                            {% if user.profile.user_type == 'headman' or user.profile.user_type == 'teacher' %}
                            <form action='' method='POST'>{% csrf_token %}
                                <div>
                                    <button class="button_main_empty" type='submit' title="Передвинуть вверх по очереди" name='queue_move_up' value="{{user_in_queue.uiq_user_id}}">▲</button>
                                    <button class="button_main_empty" type='submit' title="Передвинуть вниз по очереди" name='queue_move_down' value="{{user_in_queue.uiq_user_id}}">▼</button>
                                    <button class="button_main_empty" type='submit' title="Выкинуть из очереди" name='queue_user_delete' value="{{user_in_queue.uiq_user_id}}">✖</button>
                                </div>
                            </form>
                            {% endif %}
                            {% if user_in_queue.uiq_want_to_swap and user_in_queue.uiq_user_id != current_user.uiq_user_id and user.id == current_user.uiq_user_id%}
                                <form action='' method='POST'> {% csrf_token %}
                                    <button class="button_main_empty" type='submit' title="Поменяться местами с выбранным человеком" name='queue_swap' value="{{user_in_queue.uiq_user_id}}">Махнуться местами</button>
                                </form>
                            {% endif %}
                            {% if current_user and user_in_queue.uiq_user_id == current_user.uiq_user_id %}
                                <form action='' method='POST'> {% csrf_token %}
                                    <button class="button_main_empty" type='submit' title="Изменить состояние 'хочу войти в очередь'" name='queue_swap_state'>
                                        {% if current_user.uiq_want_to_swap %}
                                            Не хочу меняться местами
                                        {% else %}
                                            Хочу поменяться местами
                                        {% endif %}
                                    </button>
                                </form>
                            {% endif %}
                            {% if user_in_queue.uiq_want_to_swap and user_in_queue.uiq_user_id == current_user.uiq_user_id %}
                                <small>Вы готовы поменятся местами</small>
                            {% endif%}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                </table>
        {% else %}
        <table class="table">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Имя</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Группа</th>
                <th scope="col">Доп. информация</th>
                <th scope="col">Управление</th>
                </tr>
            </thead>
        </table>
        <h3>Эта очередь пустая</h3>
        {% endif %}
        {% if user.id == current_user.uiq_user_id %}
            <form action='' method='POST'> {% csrf_token %}
                <button class="button_main_empty" type='submit' title="Выйти из очереди" name='queue_exit'>Выпрыгнуть</button>
            </form>
        {% endif %}
        {% if user.profile.user_type == 'headman' or user.profile.user_type == 'teacher' %}
            <form action='' method='POST'> {% csrf_token %}
                <div>
                    {% if not queue_delete_start %}
                        <button class="button_main_empty" type='submit' title="Удалить очередь" name='queue_delete_start'>Удалить очередь</button>
                    {% else %}
                        <p>Уверены?</p>
                        <button class="button_main_empty" type='submit' title="Удалить" name='queue_delete_confirm_true' value="{{queue.queue_id}}">Да</button>
                        <button class="button_main_empty" type='submit' title="Отмена" name='queue_delete_confirm_false'>Нет</button>
                    {% endif %}
                </div>
            </form>
        {% endif %}
    </div>
    <div class="col-sm-5">
        <div class="row container">
            {% if user.username != '' %}
            <div class="content-section shadow container">
                <div class="row">
                    <div class="col-sm-6">
                        <div style="align-self: center;">
                            {% if user.id != current_user.uiq_user_id %}
                                <p class='text-muted'>Войти в очередь.
                                    {% if user_can_enter %}
                                        <form action='' method='POST'> {% csrf_token %}
                                            <button class="button_main_empty" type='submit' title="Перейти на последнее место в очереди" name='queue_enter'>Запрыгнуть в очередь</button>
                                            <fieldset>
                                                {{ queue_enter_form|crispy }}
                                                {{ priorities_form|crispy }}
                                            </fieldset>
                                        </form>
                                    {% else %}
                                        <h3>Сейчас вы не можете войти, очередь будет доступна только через {{user_can_enter_remain}}</h3>
                                    {% endif %}
                                </p>
                            {% else %}
                                <p class='text-muted'>Изменить свою информацию.
                                    {% if current_user %}
                                        <form action='' method='POST'> {% csrf_token %}
                                            <button class="button_main_empty" style="justify-self: center;" type='submit' title="Изменить информацию о себе в очереди" name='queue_change_info'>изменить информацию</button>
                                            <input type="text" name="uiq_info" style="margin-top: 10px; margin-bottom: 10px; width: 80%;">
                                            <fieldset>
                                                {{ queue_enter_form|crispy }}
                                                {{ priorities_form|crispy }}
                                            </fieldset>
                                        </form>
                                    {% endif %}
                                </p>
                            {% endif %}
                        </div>
                    </div>
                    {% if queue.queue_priorities%}
                    <div class="col-sm-6">
                        <p class='text-muted'> Порядок приоритетов
                            <ul class="list-group">
                                {% if user.profile.user_type == 'teacher' or user.profile.user_type == 'headman' %}
                                    <form action="" method="POST" style="align-self: center; padding-bottom: 10px;"> {% csrf_token %}
                                        <button class="button_main_empty" type="submit" name="sort_by_enter_time_change" id="sort_by_enter_time_change" title="Изменить принцип стортировки">
                                            {% if queue.queue_sort_by_enter_time %}
                                                Сортировать по приоритетам
                                            {% else %}
                                                Сортировать по времени вхождения
                                            {% endif %}
                                        </button>
                                    </form>
                                {% endif%}
                                {% if not queue.queue_sort_by_enter_time %}
                                    {% for priority in queue_priorities %}
                                        <li class="list-group-item {% if queue.queue_sort_by_enter_time %}sort_by_enter_time disabled{% endif %}">
                                            {{priority}}  
                                            {% if user.profile.user_type == 'teacher' or user.profile.user_type == 'headman' %}
                                                <div style="float: right">
                                                    <form action="" method="POST"> {% csrf_token %}
                                                        <button class="button_main_empty" type='submit' title="Передвинуть приоритет вверх" name='queue_priority_move_up' value="{{priority}}">▲</button>
                                                        <button class="button_main_empty" type='submit' title="Передвинуть приоритет вниз" name='queue_priority_move_down' value="{{priority}}">▼</button>
                                                    </form>
                                                </div>
                                            {% endif %}
                                        </li>
                                    {% endfor%}
                                {% else %}
                                    <p style="align-self: center;">Отключено</p>
                                {% endif%}
                            </ul>
                        </p>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="content-section shadow container">
                <div class="row">
                    <div class="col-sm">
                        <div class="container-chat">
                            <h1>События очереди</h1>
                            <div class="chat-container">
                                {% for message in chat_messages %}
                                    <div class="message shadow {% if message.user.type == 'teacher' %} message-teacher {% elif message.user.id == user.id %} message-you {% else %} message-other {% endif %}">
                                        <div >{{message.user.first_name}} {{message.user.last_name}}</div>
                                        <div class="datetime">{{message.date}}</div>
                                        <p>{{message.text}}</p>
                                    </div>
                                {% endfor %}
                            </div>
                            <form class="send-message-form" action="" method="POST"> {% csrf_token %}
                                <input type="text" name="queue_message_send" placeholder="Enter чтобы отправить">
                                <button class="button_main_empty" type="submit">Отправить</button>
                            </form>
                        </div>  
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

vl/templates/lab_queue/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} Вход {% endblock %}

{% block content %}

    <div>
        <form action="" method="POST">
            {% csrf_token %}
            <legend>Войти</legend>
            <fieldset>
                {{ form|crispy }}
            </fieldset>
            <div>
                <button class="button_main_empty" type="submit">Войти</button>
            </div>
        </form>
        <div>
            <small>
                Ещё не зарегистрированы ? <a href="{% url 'lab_queue:register' %}">Зарегистрироваться</a>
            </small>
        </div>
    </div>

{% endblock %}

vl/templates/lab_queue/logout.html
{% extends 'base.html' %}

{% block title %} Выход {% endblock %}

{% block content %}

    <div>
        <h2>Вы вышли из аккаунта, надоело быть в очередях?</h2>
        <p>Нет, я <a href="{% url 'lab_queue:login' %}">зайду ещё раз</a></p>
    </div>

{% endblock %}

vl/templates/lab_queue/mainlist.html
{% extends 'base.html' %}

{% block title %} Список всех очередей {% endblock %}

{% block content %}
    <!-- <a href="{% url 'lab_queue:newqueue' %}">Новая очередь</a> -->
    {% if overall_list %}
            <table class="table table-responsive table-striped table-hover table-light " style="background-color: #fafafa;">
                <thead>
                  <tr>
                    <th scope="col">Название</th>
                    <th scope="col">Целевая группа</th>
                    <th scope="col">Дата создания</th>
                    <th scope="col">Доп. информация</th>
                  </tr>
                </thead>
                <tbody>
                    {% for item in overall_list %}
                        <tr>
                            <th scope="row"><a href="{% url 'lab_queue:detail' item.queue_id %}">{{item.queue_title}}</a><br></th>
                            <td>{{item.queue_group}}</td>
                            <td>{{item.queue_create_date}}</td>
                            <td>{{item.queue_info}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        
    {% else %}
        В данный момент очередей нет
    {% endif %}
{% endblock %}